default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

  pool: 5

development:
  <<: *default
  database: macsailing_development

test:
  <<: *default
  database: macsailing_test


production:
  <<: *default
  database: macsailing_production
  username: macsailing
  password: <%= ENV['REACT-RAILS-BLOG_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
