# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927458855dba2433fca3c653dfda34f5fe0a11eb6c3fe0dc8decd3c21d58623666c29867851721e434c640e04b505c58ea435e8660db2500754f459c30c853b2

test:
  secret_key_base: 111ba0c43ab204910a3290316e6dd067b23e4dd904640d7c31b45040f59881ed8b6308ceff501b0d375fbf14eecd60f8132418b59fb87c7baf3204cc78c129b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
